version: '3.1'

services:

    db:
        image: postgres:10
        restart: always
        ports:
            - 5437:5432
        environment:
            POSTGRES_USER: alexy
            POSTGRES_PASSWORD: alexy100
            POSTGRES_DB: alexydb
    adminer:
        image: adminer
        restart: always
        ports:
            - 8087:8080
